name: Deploy Branch Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write
  deployments: write
  checks: write
  id-token: write

jobs:
  # Check if PR is from a fork - forks don't have access to secrets
  check-fork:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - name: Check if PR is from fork
        id: check
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
            echo "🔀 PR is from a fork: ${{ github.event.pull_request.head.repo.full_name }}"
            echo "⏭️ Skipping deployment (use deploy-fork-preview.yml with 'deploy-preview' label instead)"
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
            echo "✅ PR is from same repository"
          fi

  # Note: Fork notification is handled by deploy-fork-preview.yml to avoid permission issues
  # (pull_request trigger from forks cannot write comments even with permissions specified)

  deploy:
    needs: check-fork
    if: needs.check-fork.outputs.is_fork == 'false'
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      deployment_type: 'branch'
      branch_name: ${{ github.head_ref }}
      pr_number: ${{ github.event.number }}

  test:
    needs: [check-fork, deploy]
    if: needs.check-fork.outputs.is_fork == 'false'
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      api_url: ${{ needs.deploy.outputs.api_url }}
      web_url: ${{ needs.deploy.outputs.web_url }}
      deployment_type: 'branch'
      branch_name: ${{ github.head_ref }}
      pr_number: ${{ github.event.number }}
