name: Deploy Fork Preview

on:
  pull_request_target:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  deployments: write
  checks: write
  id-token: write

jobs:
  # Check if this is actually a fork PR (skip if same-repo)
  check-fork:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.check.outputs.is_fork }}
    steps:
      - name: Check if PR is from fork
        id: check
        run: |
          if [ "${{ github.event.pull_request.head.repo.full_name }}" != "${{ github.repository }}" ]; then
            echo "is_fork=true" >> $GITHUB_OUTPUT
            echo "🔀 Fork PR detected - will deploy with maintainer approval"
            echo "📍 From: ${{ github.event.pull_request.head.repo.full_name }}"
            echo "⚠️ Note: GitHub requires maintainer approval for first-time contributors"
          else
            echo "is_fork=false" >> $GITHUB_OUTPUT
            echo "⏭️ Same-repo PR - skipping (handled by deploy-branch-preview.yml)"
          fi

  deploy:
    needs: check-fork
    if: needs.check-fork.outputs.is_fork == 'true'
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      deployment_type: 'branch'
      branch_name: ${{ github.event.pull_request.head.ref }}
      pr_number: ${{ github.event.number }}

  test:
    needs: [check-fork, deploy]
    if: needs.check-fork.outputs.is_fork == 'true'
    uses: ./.github/workflows/reusable-test.yml
    secrets: inherit
    with:
      api_url: ${{ needs.deploy.outputs.api_url }}
      web_url: ${{ needs.deploy.outputs.web_url }}
      deployment_type: 'branch'
      branch_name: ${{ github.event.pull_request.head.ref }}
      pr_number: ${{ github.event.number }}
